# Generated by Django 5.2.3 on 2025-07-01 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapandsell', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='Set an Address', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='another_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('DAMAGED', 'Damaged')], default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_of_product',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('iPhone', 'Iphone'), ('Android', 'Android'), ('Laptop', 'Laptop')], default='iPhone', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('SWAP', 'Swap'), ('SELL', 'Sell')], default='SWAP', max_length=10),
        ),
    ]
