# Generated by Django 5.2.3 on 2025-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapandsell', '0002_alter_product_options_product_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
